import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { Body } from "./body";
import { Footer } from "./footer";
import { Header } from "./header";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Rohit Tokala</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Header />
        <Body />
        <Footer />
      </div>
    </>
  );
};

export default Home;
