import { type NextPage } from "next";
import Head from "next/head";
import { Body } from "../components/body";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Rohit Tokala</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <link rel="preconnect" href="https://fonts.googleapis.com" /> */}
        {/* <link
          href="https://fonts.googleapis.com/css2?family=Expletus+Sans:wght@600&display=swap"
          rel="stylesheet"
        /> */}
      </Head>
      <Body />
    </>
  );
};

export default Home;
