import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";

export function Header() {
  const router = useRouter();
  const currentRoute = router.pathname;

  return (
    <>
      <Head>
        <title>Rohit Tokala</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Expletus+Sans:wght@600&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div className=" flex flex-row items-center justify-between">
        <Link href={"/"} className=" font-Expletus text-xl">
          Rohit Tokala
        </Link>
        <ul className=" flex flex-row items-center gap-3 text-primary">
          <li>
            <Link
              className={` rounded-xl p-2 hover:bg-shadow  ${
                currentRoute === "/" ? `border bg-shadow font-medium` : ""
              }`}
              href="/"
            >
              Home
            </Link>
          </li>
          <li>
            <Link
              className={` rounded-xl p-2 hover:bg-shadow ${
                currentRoute === "/about" ? `border bg-shadow font-medium` : ""
              }`}
              href="/about"
            >
              About
            </Link>
          </li>
          <li>
            <Link
              className={` rounded-xl p-2 hover:bg-shadow ${
                currentRoute === "/projects"
                  ? `border bg-shadow font-medium`
                  : ""
              }`}
              href={"/projects"}
            >
              Projects
            </Link>
          </li>
          <li>
            <Link
              className={` rounded-xl p-2 hover:bg-shadow  ${
                currentRoute === "/resume" ? `border bg-shadow font-medium` : ""
              }`}
              href={"/resume"}
            >
              Resume
            </Link>
          </li>
          <li>
            <Link
              className={` rounded-xl border border-primary p-2 hover:bg-shadow hover:text-primary ${
                currentRoute === "/contact"
                  ? "border bg-shadow font-medium "
                  : "bg-primary text-white "
              }`}
              href={"/contact"}
            >
              Contact Me
            </Link>
          </li>
        </ul>
      </div>
    </>
  );
}
